### ISSUE TITLE
[BUG] Git hook for autoformatting markdown tables not working

### ISSUE THREAD

**Issue by johnsonfoo** [NTU-DSAI/DSAI-Projects#3]
**Describe the bug**
Tables in markdown files do not seem to be formatted correctly even with git hook markdown table formatting enabled.

**Screenshots**
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/37036242/156507703-abb3fd4b-7472-4254-a2c9-45003c5c7cf8.png">
Changes like above should be avoided.

**Additional context**
Low priority issue, investigations required.

**Comment by johnsonfoo** [comment]
@majulahsingapuri Do you have the specific git hook config file?

**Comment by majulahsingapuri** [comment]
the config is in `./pre-commit-config.yaml`. I'm using [pre-commit](pre-commit.com) as the tool that handles the hook and prettier as the executable. Prettier to my knowledge does not handle markdown tables thus causing the issue. It might also be that when committing to the repo, you need to have pre-commit installed on your machine and that might be getting bypassed somehow?

**Comment by johnsonfoo** [comment]
Found [mdformat-tables](https://github.com/executablebooks/mdformat-tables) which is part of [mdformat](https://github.com/executablebooks/mdformat) that is what we want to do.

> Prettier suffers from numerous bugs, many of which cause changes in Markdown AST and rendered HTML. Many of these bugs are a consequence of using remark-parse v8.x as Markdown parser which, according to the author themselves, is inferior to markdown-it used by mdformat. remark-parse v9.x is advertised as CommonMark compliant and presumably would fix many of the issues, but is not used by Prettier (v2.4.0) yet.

From the FAQ for mdformat.

Haven't tested mdformat-tables out yet but the test case provided under [test](https://github.com/executablebooks/mdformat-tables/blob/master/tests/fixtures.md) looks like what we need. Will investigate whether it can be used alongside prettier.

**Comment by johnsonfoo** [comment]
I believe the following example will illustrate how pre-commit works.

<img width="855" alt="image" src="https://user-images.githubusercontent.com/37036242/156581674-a860aaa7-4868-4142-9b0b-7a335d0ded06.png">

**Comment by majulahsingapuri** [comment]
@johnsonfoo good catch! I have made it explicit in the README for now. I will set up a Github Action to enforce this styling in a future commit.
